# Generated by Django 5.2.1 on 2025-05-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_cancellazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='data_richiesta_cancellazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dati_anonimizzati',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='richiesta_cancellazione',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='stato',
            field=models.CharField(choices=[('attivo', 'Attivo'), ('sospeso', 'Sospeso'), ('cancellato', 'Cancellato')], default='attivo', max_length=20),
        ),
    ]
