# Generated by Django 6.0.3 on 2026-03-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('utenti', '0003_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crediti',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CreditoMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=80)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crediti_movimenti', to='utenti.user')),
            ],
            options={
                'verbose_name': 'Movimento Crediti',
                'verbose_name_plural': 'Movimenti Crediti',
                'ordering': ['-created_at'],
            },
        ),
    ]

