# Generated by Django 6.0.3 on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('utenti', '0004_user_crediti_and_movimenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
        migrations.AddField(
            model_name='user',
            name='iban_intestatario',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]

