# Generated by Django 6.0.3 on 2026-03-29 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0005_user_iban_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoRicarica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crediti', models.PositiveIntegerField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('confermata', 'Confermata'), ('annullata', 'Annullata')], default='in_attesa', max_length=20)),
                ('causale', models.CharField(blank=True, default='', max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crediti_ricariche_confermate', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crediti_ricariche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ricarica Crediti',
                'verbose_name_plural': 'Ricariche Crediti',
                'ordering': ['-created_at'],
            },
        ),
    ]
