# Generated by Django 6.0.3 on 2026-03-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0006_creditoricarica'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoricarica',
            name='ricevuta',
            field=models.FileField(blank=True, null=True, upload_to='crediti/ricariche/%Y/%m/'),
        ),
    ]
