version: '3.8'

# Docker Compose ottimizzato per VPS Webdock Nano4
# Configurazione per 1-2GB RAM e risorse limitate

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: domanda_software
      POSTGRES_USER: domanda_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # Ottimizzazioni PostgreSQL per RAM limitata
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - app-network
    # Configurazione resource limits per RAM limitata
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    # PostgreSQL ottimizzato per basse risorse
    command: >
      postgres
      -c shared_buffers=64MB
      -c effective_cache_size=128MB
      -c maintenance_work_mem=16MB
      -c work_mem=2MB
      -c max_connections=20
      -c checkpoint_completion_target=0.9
      -c wal_buffers=2MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U domanda_user -d domanda_software"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.nano
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=config.nano_settings
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - DB_NAME=domanda_software
      - DB_USER=domanda_user
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=${DOMAIN_NAME},www.${DOMAIN_NAME}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "127.0.0.1:8000:8000"
    # Resource limits per backend Django
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nano
      args:
        - VITE_API_URL=https://${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "127.0.0.1:3000:80"
    # Resource limits per frontend Nginx
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.nano.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    # Resource limits per Nginx
    deploy:
      resources:
        limits:
          memory: 32M
        reservations:
          memory: 16M
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # SSL con renewal più leggero
  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Renewal ogni 24h invece di 12h per risparmiare risorse
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge 