# Generated by Django 5.2 on 2025-05-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(help_text='Testo della testimonianza o ringraziamento')),
                ('autore', models.CharField(help_text="Nome o pseudonimo dell'autore", max_length=100)),
                ('tipo_autore', models.CharField(choices=[('cliente', 'Cliente'), ('fornitore', 'Fornitore'), ('azienda', 'Azienda'), ('startup', 'Startup'), ('altro', 'Altro')], default='cliente', max_length=20)),
                ('attivo', models.BooleanField(default=True, help_text='Se la testimonianza è visibile sulla home page')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('ordine', models.IntegerField(default=0, help_text='Ordine di visualizzazione (i numeri più bassi appaiono prima)')),
            ],
            options={
                'verbose_name': 'Testimonianza',
                'verbose_name_plural': 'Testimonianze',
                'ordering': ['ordine', '-data_creazione'],
            },
        ),
    ]
