# Generated by Django 5.2 on 2025-05-16 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progetti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_inviati', to=settings.AUTH_USER_MODEL)),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi', to='progetti.progetto')),
            ],
        ),
    ]
