# Generated by Django 5.2 on 2025-05-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaggi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messaggio',
            options={'verbose_name': 'Messaggio', 'verbose_name_plural': 'Messaggi'},
        ),
    ]
