# Generated by Django 5.2 on 2025-05-16 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progetti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo_totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commissione_cliente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commissione_fornitore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importo_fornitore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_transazione', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('completata', 'Completata'), ('rimborsata', 'Rimborsata')], default='in_attesa', max_length=20)),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transazioni', to='progetti.progetto')),
            ],
        ),
    ]
