# Generated by Django 5.2 on 2025-05-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transazioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transazione',
            options={'verbose_name': 'Transazione', 'verbose_name_plural': 'Transazioni'},
        ),
    ]
