# Generated by Django 6.0.3 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transazioni', '0003_messaggio'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transazione',
            constraint=models.UniqueConstraint(fields=('progetto',), name='unique_transazione_per_progetto'),
        ),
    ]

