# Generated by Django 5.2 on 2025-05-16 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offerte', '0001_initial'),
        ('richieste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('in_corso', 'In corso'), ('completato', 'Completato'), ('in_contestazione', 'In contestazione'), ('annullato', 'Annullato')], default='in_corso', max_length=20)),
                ('data_inizio', models.DateTimeField(auto_now_add=True)),
                ('data_fine', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetti_cliente', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetti_fornitore', to=settings.AUTH_USER_MODEL)),
                ('offerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetti', to='offerte.offerta')),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetti', to='richieste.richiesta')),
            ],
        ),
    ]
