# Generated by Django 5.2 on 2025-05-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progetto',
            options={'verbose_name': 'Progetto', 'verbose_name_plural': 'Progetti'},
        ),
    ]
