# Generated by Django 5.2.1 on 2025-05-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0002_alter_progetto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progetto',
            name='stato',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('prima_release', 'Prima release'), ('completato', 'Completato'), ('in_contestazione', 'In contestazione'), ('annullato', 'Annullato')], default='bozza', max_length=20),
        ),
    ]
