# Generated by Django 5.2.1 on 2025-05-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0003_alter_progetto_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='bozza_cliente_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progetto',
            name='bozza_fornitore_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progetto',
            name='consegna_cliente_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progetto',
            name='consegna_fornitore_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progetto',
            name='pagamento_admin_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progetto',
            name='pagamento_cliente_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progetto',
            name='stato',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('prima_release', 'Prima release'), ('pagamento', 'Pagamento'), ('completato', 'Completato'), ('in_contestazione', 'In contestazione'), ('annullato', 'Annullato')], default='bozza', max_length=20),
        ),
        migrations.CreateModel(
            name='StepPersonalizzato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('completato_fornitore', models.BooleanField(default=False)),
                ('completato_cliente', models.BooleanField(default=False)),
                ('data_fornitore', models.DateTimeField(blank=True, null=True)),
                ('data_cliente', models.DateTimeField(blank=True, null=True)),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_personalizzati', to='progetti.progetto')),
            ],
            options={
                'ordering': ['ordine'],
            },
        ),
    ]
