# Generated by Django 5.2 on 2025-05-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0005_progetto_archiviato_progetto_archiviato_da_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='bonifico_fornitore_ok',
            field=models.BooleanField(default=False, help_text='Conferma ricezione bonifico da parte del fornitore'),
        ),
    ]
