# Generated by Django 6.0.3 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('progetti', '0006_progetto_bonifico_fornitore_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='tipo_progetto',
            field=models.CharField(
                choices=[('richiesta_classica', 'Da richiesta classica'), ('prodotto_acquistato', 'Da prodotto acquistato')],
                default='richiesta_classica',
                help_text="Indica l'origine del progetto",
                max_length=50,
            ),
        ),
    ]

