# Generated by Django 6.0.3 on 2026-03-26

from django.db import migrations


def forwards(apps, schema_editor):
    Progetto = apps.get_model('progetti', 'Progetto')
    Progetto.objects.filter(stato='in_corso').update(stato='bozza')


class Migration(migrations.Migration):
    dependencies = [
        ('progetti', '0007_progetto_tipo_progetto'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

