# Generated by Django 6.0.3 on 2026-03-28 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerte', '0003_offerta_in_attesa_approvazione'),
        ('progetti', '0008_normalize_stato_in_corso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progetto',
            name='offerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progetti', to='offerte.offerta'),
        ),
    ]
