# Generated by Django 6.0.3 on 2026-03-28 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0009_alter_progetto_offerta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='contestazione_aperta_da',
            field=models.ForeignKey(blank=True, help_text='Utente che ha aperto la contestazione', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestazioni_aperte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progetto',
            name='contestazione_motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='progetto',
            name='contestazione_risolta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progetto',
            name='contestazione_risoluzione_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
