# Generated by Django 6.0.3 on 2026-03-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0010_progetto_contestazione_aperta_da_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='pagamento_cliente_ricevuta',
            field=models.FileField(blank=True, null=True, upload_to='progetti/pagamenti/%Y/%m/'),
        ),
    ]
