# Generated by Django 6.0.3 on 2026-03-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0011_progetto_pagamento_cliente_ricevuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='bonifico_fornitore_ricevuta',
            field=models.FileField(blank=True, null=True, upload_to='progetti/bonifici/%Y/%m/'),
        ),
    ]
