# Generated by Django 6.0.3 on 2026-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0012_progetto_bonifico_fornitore_ricevuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='bonifico_admin_ok',
            field=models.BooleanField(default=False, help_text='Bonifico inviato da SoftMatch (admin)'),
        ),
    ]
