# Generated by Django 5.2 on 2025-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottopronto',
            name='immagine',
            field=models.ImageField(blank=True, help_text='Immagine del prodotto (formato consigliato: JPG/PNG, dimensione massima: 2MB, proporzioni: 16:9)', null=True, upload_to='prodotti_pronti/'),
        ),
    ]
