# Generated by Django 5.2 on 2025-05-24 16:10

import prodotti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0002_prodottopronto_immagine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodottopronto',
            options={'ordering': ['-data_pubblicazione'], 'verbose_name': 'Prodotto Pronto', 'verbose_name_plural': 'Prodotti Pronti'},
        ),
        migrations.AddField(
            model_name='prodottopronto',
            name='categoria',
            field=models.CharField(choices=[('template', 'Template/Temi'), ('plugin', 'Plugin/Estensioni'), ('script', 'Script/Codici'), ('software', 'Software Completi'), ('app', 'App Mobile'), ('servizio', 'Servizi/Consulenze')], default='software', help_text='Categoria del prodotto', max_length=50),
        ),
        migrations.AddField(
            model_name='prodottopronto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prezzo di vendita del prodotto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='prodottopronto',
            name='immagine',
            field=models.ImageField(blank=True, help_text='Immagine del prodotto (max 5MB, formati: JPG, PNG, WEBP)', null=True, upload_to=prodotti.models.prodotto_image_path, validators=[prodotti.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='prodottopronto',
            name='link_demo',
            field=models.URLField(blank=True, help_text='URL alla versione demo del prodotto'),
        ),
        migrations.AlterField(
            model_name='prodottopronto',
            name='titolo',
            field=models.CharField(max_length=200),
        ),
    ]
