# Generated by Django 5.2.1 on 2025-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0003_alter_prodottopronto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottopronto',
            name='categoria',
            field=models.CharField(
                choices=[
                    ('template', 'Template/Temi'),
                    ('plugin', 'Plugin/Estensioni'),
                    ('script', 'Script/Codici'),
                    ('software', 'Software Completi'),
                    ('app', 'App Mobile'),
                    ('servizio', 'Servizi/Consulenze')
                ],
                default='software',
                help_text='Categoria del prodotto',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='prodottopronto',
            name='prezzo',
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                help_text='Prezzo di vendita del prodotto',
                max_digits=10
            ),
        ),
    ]
