# Generated by Django 5.2 on 2025-05-16 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('richieste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_offerta', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('inviata', 'Inviata'), ('accettata', 'Accettata'), ('rifiutata', 'Rifiutata'), ('annullata', 'Annullata')], default='inviata', max_length=20)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to=settings.AUTH_USER_MODEL)),
                ('richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='richieste.richiesta')),
            ],
        ),
    ]
