# Generated by Django 5.2 on 2025-05-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerta',
            options={'verbose_name': 'Offerta', 'verbose_name_plural': 'Offerte'},
        ),
    ]
