# Generated by Django 5.2.1 on 2025-05-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerte', '0002_alter_offerta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='in_attesa_approvazione',
            field=models.BooleanField(default=False),
        ),
    ]
