# Generated by Django 5.2 on 2025-06-01 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Categoria')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('icon', models.CharField(default='FaQuestionCircle', max_length=50, verbose_name='Icona')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria FAQ',
                'verbose_name_plural': 'Categorie FAQ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Domanda')),
                ('answer', models.TextField(verbose_name='Risposta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizzazioni')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Voti Utili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creata da')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faq.faqcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['category__order', 'order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='FAQComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Commento')),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('approved', 'Approvato'), ('rejected', 'Rifiutato')], default='pending', max_length=20, verbose_name='Stato')),
                ('is_question', models.BooleanField(default=False, verbose_name='È una domanda')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Mi Piace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='faq.faq', verbose_name='FAQ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Commento FAQ',
                'verbose_name_plural': 'Commenti FAQ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(verbose_name='Risposta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reply', to='faq.faqcomment', verbose_name='Commento')),
            ],
            options={
                'verbose_name': 'Risposta Admin',
                'verbose_name_plural': 'Risposte Admin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='faq.faqcomment', verbose_name='Commento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Like Commento',
                'verbose_name_plural': 'Like Commenti',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='FAQHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='faq.faq', verbose_name='FAQ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Voto Utilità',
                'verbose_name_plural': 'Voti Utilità',
                'unique_together': {('user', 'faq')},
            },
        ),
    ]
