# Generated by Django 5.2 on 2025-05-16 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('aperta', 'Aperta'), ('in_lavorazione', 'In lavorazione'), ('completata', 'Completata'), ('annullata', 'Annullata')], default='aperta', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
