# Generated by Django 5.2 on 2025-05-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richieste', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='richiesta',
            options={'verbose_name': 'Richiesta', 'verbose_name_plural': 'Richieste'},
        ),
    ]
