# Generated by Django 5.2.1 on 2025-05-24 15:09

import richieste.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richieste', '0002_alter_richiesta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='immagine',
            field=models.ImageField(blank=True, help_text='Immagine opzionale (max 5MB, formati: JPG, PNG, WEBP)', null=True, upload_to=richieste.models.richiesta_image_path, validators=[richieste.models.validate_image_size]),
        ),
    ]
