# Generated by Django 5.2 on 2025-05-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richieste', '0003_richiesta_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='tipo_software',
            field=models.CharField(choices=[('crm', 'CRM - Customer Relationship Management'), ('gestionale', 'Gestionale/ERP - Enterprise Resource Planning'), ('ecommerce', 'E-commerce - Negozio Online'), ('sito_web', 'Sito Web - Vetrina/Corporate'), ('app_mobile', 'App Mobile - iOS/Android'), ('web_app', 'Web Application - Applicazione Web'), ('software_desktop', 'Software Desktop - Applicazione Desktop'), ('api_servizi', 'API/Servizi Web - Integrazione Sistemi'), ('automazione', 'Automazione Processi - Workflow'), ('business_intelligence', 'Business Intelligence - Analisi Dati'), ('altro', 'Altro - Specifica nella descrizione')], default='altro', help_text='Categoria del software richiesto', max_length=50),
        ),
    ]
