# Generated by Django 4.2 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('richieste', '0004_richiesta_tipo_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='is_prodotto_acquistato',
            field=models.BooleanField(default=False, help_text='Indica se questa richiesta è stata creata automaticamente da un acquisto di prodotto'),
        ),
    ]

