# Generated by Django 6.0.3 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('richieste', '0005_richiesta_is_prodotto_acquistato'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='skill_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='skill_tags_search',
            field=models.TextField(blank=True, default=''),
        ),
    ]

