server {
  listen 80;
  server_name app.softmatch.it api.softmatch.it softmatch.it www.softmatch.it 193.181.208.112;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name softmatch.it www.softmatch.it 193.181.208.112;

  ssl_certificate /etc/letsencrypt/live/softmatch.it/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/softmatch.it/privkey.pem;

  return 301 https://app.softmatch.it$request_uri;
}

server {
  listen 443 ssl;
  server_name app.softmatch.it;

  ssl_certificate /etc/letsencrypt/live/softmatch.it/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/softmatch.it/privkey.pem;

  client_max_body_size 20m;

  location / {
    proxy_pass http://frontend:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
  }

  location /api/ {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
  }

  location /static/ {
    alias /var/www/staticfiles/;
  }

  location /media/ {
    alias /var/www/media/;
  }
}

server {
  listen 443 ssl;
  server_name api.softmatch.it;

  ssl_certificate /etc/letsencrypt/live/softmatch.it/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/softmatch.it/privkey.pem;

  client_max_body_size 20m;

  location /static/ {
    alias /var/www/staticfiles/;
  }

  location /media/ {
    alias /var/www/media/;
  }

  location / {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_read_timeout 120;
    proxy_send_timeout 120;
  }
}

