# Generated by Django 6.0.3 on 2026-03-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='core_audite_action_3957f4_idx',
            old_name='core_audite_action_70de3c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='core_audite_target__cc0e25_idx',
            old_name='core_audite_target__ddc3d0_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='core_audite_progett_4c776b_idx',
            old_name='core_audite_progett_198a5a_idx',
        ),
    ]
