# Generated by Django 6.0.4 on 2026-04-10 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_audite_action_70de3c_idx_core_audite_action_3957f4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('messaggio', models.TextField()),
                ('letta', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(choices=[('info', 'Informazione'), ('success', 'Successo'), ('warning', 'Attenzione'), ('danger', 'Errore')], default='info', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
                'ordering': ('-data_creazione',),
            },
        ),
    ]
